apiVersion: v1
kind: Secret
metadata:
  name: application-devteam-a1
  namespace: devteam-a1
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/tppalani/devteam-a1.git
  insecure: "false" # Ignore validity of server's TLS certificate. Defaults to "false"
  forceHttpBasicAuth: "true" # Skip auth method negotiation and force usage of HTTP basic auth. Defaults to "false"
  enableLfs: "true" # Enable git-lfs for this repository. Defaults to "false"
